name: "Build"
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
      - name: "Build"
        run: npm run build
